<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>latest</LangVersion>
        <AnalysisLevel>latest-recommended</AnalysisLevel>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Diagnostics" Version="8.2.2" />
        <PackageReference Include="CommunityToolkit.HighPerformance" Version="8.2.2" />
        <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.1.303">
            <PrivateAssets>All</PrivateAssets>
        </PackageReference>
    </ItemGroup>
</Project>